# Generated by Django 5.1.7 on 2025-03-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bursary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('eligibility_criteria', models.TextField()),
                ('application_deadline', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
