# Generated by Django 5.2 on 2025-05-30 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_topic_job_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.topic'),
            preserve_default=False,
        ),
    ]
